Document: bloonix-plugins-lighttpd
Title: Debian bloonix-plugins-lighttpd Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-lighttpd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-lighttpd/bloonix-plugins-lighttpd.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-lighttpd/bloonix-plugins-lighttpd.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-lighttpd/bloonix-plugins-lighttpd.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-lighttpd/html/index.html
Files: /usr/share/doc/bloonix-plugins-lighttpd/html/*.html


